name: spack mobject@develop+bedrock

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Sources
      uses: actions/checkout@v3

    - name: Checkout Spack
      uses: actions/checkout@v3
      with:
        repository: hyoklee/spack
        path: ./spack
    - name: Checkout mochi-spack-packages
      uses: actions/checkout@v3
      with:
        repository: mochi-hpc/mochi-spack-packages
        path: ./mochi-spack-packages
    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack repo add ./mochi-spack-packages
        spack install --test root mobject@develop+bedrock
        spack load mobject
        sudo . ./spack/share/spack/setup-env.sh && spack view copy -i /usr/local mobject
        ls /usr/local/lib/
        mkdir build
        cd build
        cmake ..
        make
        