name: spack mobject+bedrock

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Sources
      uses: actions/checkout@v3

    - name: Checkout Spack
      uses: actions/checkout@v3
      with:
        repository: spack/spack
        path: ./spack
    - name: Checkout mochi-spack-packages
      uses: actions/checkout@v3
      with:
        repository: mochi-hpc/mochi-spack-packages
        path: ./mochi-spack-packages
    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack repo add ./mochi-spack-packages
        spack install --test root mobject@main+bedrock
        spack load mobject
        spack view copy -i /tmp mobject
        ls /tmp/lib/
        mkdir build
        cd build
        cmake ..
        make
        